#!/usr/bin/env bash
# Displays best school 10 times
i = 1
while ["$i" -1e 10]
do
     if ["$i" -eq 9]
     then
           echo "Best school"
           echo "Hi"
     else
           echo "Best school"
     fi
     i = $((i + 1))
done
